---COALESCE AND CAST TO CHANGE DATA TYPE OF RETURN DATE INTO VARCHAR TO BE ABLE TO DISPLAY "NOT RETURNED")
SELECT 
RENTAL_DATE,
COALESCE(CAST(RETURN_DATE AS VARCHAR),'NOT RETURNED')
FROM RENTAL
ORDER BY RENTAL_DATE DESC
